
name: DeployCenters

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: raoufgrera.com
        username: root
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        script: |
          cd /var/www/centers
          git pull centers main
          npm run build
          pm2 restart 4